package net.sf.mpango.game.core.events;

import net.sf.mpango.game.core.commands.Command;

/**
 * Events generated by commands.
 * @author edvera
 *
 */
public abstract class CommandEvent<T extends Command> extends AbstractEvent<T> {

	/**
	 * Constructor that takes a command and assigns it as the source of the event as well as the command associated to this class.
	 * @param command that generated the event.
	 */
	public CommandEvent(final T command) {
		super(command);
	}

	/**
	 * Method that returns the command that generated the event.
	 * @return Command that generated the event.
	 */
	public T getCommand() {
		return getSource();
	}
	
	private static final long serialVersionUID = 6207407251929257717L;
}
